### ISSUE TITLE
Change from contenteditable to `textarea`

### ISSUE THREAD

**Issue by StephanStanisic** [StephanStanisic/simple-blog#10]
Implement a system that changes from a div to textarea on click, just like the core.

See https://github.com/StephanStanisic/plugin-simpleblog/issues/4#issuecomment-540076044

**Comment by robiso** [comment]
@StephanStanisic Let me know when it's ready for some testing, would love to see how this pans out. :)

**Comment by StephanStanisic** [comment]
This has been added with commit bc3b6375dba041353ac6f27174111ec94a257915, closing issue
